version: '3.8'

networks:
  network-rotten:
    driver: bridge
    name: network-rotten

volumes:
  volume-rotten:
    name: volume-rotten


services:
  
  mongo:
    container_name: mongo
    image: mongo:4.4.3
    networks:
      - network-rotten
    #ports:
    #  - 27017:27017
    volumes:
      - volume-rotten:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PWD}
  
  app:
    container_name: app
    image: ivanjuniordocker/rotten-potatoes:1
    networks:
      - network-rotten
    ports:
      - 8080:5000
    depends_on:
      - mongo
    restart: always
    environment:
      MONGODB_DB: ${DB}
      MONGODB_HOST: mongo
      MONGODB_PORT: '27017'
      MONGODB_USERNAME: ${ROOT_USER}
      MONGODB_PASSWORD: ${ROOT_PWD}

  #Serviço para administração do banco
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    networks:
      - network-rotten
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_USER}:${ROOT_PWD}@mongo:27017/